### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by zygimantas** [mponkin/fading_edge_scrollview#11]
Could you please support null safety, so this library can be used in null safe project? Thank you.

**Comment by mponkin** [comment]
working on this and some api updates, will publish a new version in few days

**Comment by yasarthewise** [comment]
looking forwart to it.

**Comment by mponkin** [comment]
I decided to postpone major api changes based on my work with migrations last week.
Version 2.0.0 is available now with null-safety support
