### ISSUE TITLE
Non-fatal null check operator issue

### ISSUE THREAD

**Issue by Cee-Ng** [mponkin/fading_edge_scrollview#15]
Using fading_edge_scrollview 2.0.0, and I found this issue being reported quite often in our crashlytics console, which seems to point to an issue with the fact `_isScrolledToEnd` can be null based off the line it points to. 
`

> Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
>        at ScrollPosition.maxScrollExtent(ScrollPosition.java:140)
>        at _FadingEdgeScrollViewState._postFrameCallback(_FadingEdgeScrollViewState.java:206)
>        at SchedulerBinding._invokeFrameCallback(SchedulerBinding.java:1144)
>        at SchedulerBinding.handleDrawFrame(SchedulerBinding.java:1090)
>        at SchedulerBinding._handleDrawFrame(SchedulerBinding.java:998)

**Comment by alex-myznikov** [comment]
I have the same issue. It turns to be the issue originates from the ScrollPosition.maxScrollExtent, which is declared as a non-nullable in scroll_position.dart, while it still can be null in some cases. It can be fixed for now by checking _controller.position.hasContentDimensions each time before _controller.position.maxScrollExtent in fading_edge_scrollview.dart.

@mponkin Can we expect this issue to be checked and fixed any time soon? Shall I submit a pull request for it?

**Comment by mponkin** [comment]
Published version 2.0.1 with fix
@alex-myznikov Thanks for explanation. I was unable to understand the problem at first glance.
I was unable to test if fix is working, because I've never reproduced original issue, so please report if it still happen

**Comment by alex-myznikov** [comment]
Hi, thank you! I will probably try it next week and post back here about my results.
