### ISSUE TITLE
Flutter 3.0.0 is detecting issue with the library

### ISSUE THREAD

**Issue by RoyalCoder88** [mponkin/fading_edge_scrollview#16]
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/fading_edge_scrollview-2.0.1/lib/src/fading_edge_scrollview.dart:220:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Documents/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(this);

**Comment by dJani97** [comment]
Having the same issue.

In Flutter 3, WidgetsBinding.instance is no longer nullable, so the `?.` operator is no longer necessary. Please remove these operators.

Reproducible by using Flutter 3 and the latest version of this library in the same project.

**Comment by mponkin** [comment]
Fixed in version 3.0.0
Sorry for missing this issue. Been busy with other stuff and haven't seen any notifications.
Thanks to @ruslic19 for providing the PR
