### ISSUE TITLE
ERROR: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController'.

### ISSUE THREAD

**Issue by AlexitoSnow** [mponkin/fading_edge_scrollview#27]
I was using the [Marquee Package](https://pub.dev/packages/marquee) that depends on this package and I noticed that the pub.dev
shows the following error during the analysis issues.

ERROR: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController'.

![Captura de pantalla 2024-02-25 001112](https://github.com/mponkin/fading_edge_scrollview/assets/116590887/bab0723f-8dd0-4793-b7af-4c4994de5171)

When I ran my project using the marquee package, it sure enough, it showed an execution error.

**Comment by mponkin** [comment]
Thank you for pointing out the problem. I see it existed in the main Flutter channel. It's good to be prepared for upcoming changes. I've published a new version (4.1.1) with updates that fixed the static analysis issues. 

However, I believe the problem still exists in the mentioned package, as it needs to be modified for this change.

**Comment by mponkin** [comment]
Thank you for pointing out the problem. I see it existed in the main Flutter channel. It's good to be prepared for upcoming changes. I've published a new version (4.1.1) with updates that fixed the static analysis issues.

However, I believe the problem still exists in the mentioned package, as it needs to add a `controller` to `PageView` provided as `child` to `FadingEdgeScrollView.fromPageView` constructor.

**Comment by AlexitoSnow** [comment]
I recommend adding an assertion to ensure that the user adds the controller, or maybe create one if child.controller is null.
### Option A:
`assert(child.controller != null, 'Your PageView widget needs a PageController')`
### Option B:
`controller: child.controller ?? PageController()`
