### ISSUE TITLE
Support for RTL and LTR at the same time

### ISSUE THREAD

**Issue by oha2004** [mponkin/fading_edge_scrollview#7]
I have a multi language app
The package works fine with LTR using FadingEdgeScrollView.fromScrollView
But its not functional with RTL 
I think AlignmentDirectional should do the trick
Thank you for your efforts

**Comment by mponkin** [comment]
Thanks for pointing out this problem. I've fixed it in version 1.1.3

**Comment by oha2004** [comment]
You're the BEST !
